export const ADD_EVENT_SUCCESS = "ADD_EVENT_SUCCESS";
export const ADD_EVENT_ERROR = "ADD_EVENT_ERROR";

export const GET_ALL_EVENTS_SUCCESS = "GET_ALL_EVENTS_ERROR_SUCCESS";
export const GET_ALL_EVENTS_ERROR = "GET_ALL_EVENTS_ERROR";

export const APPLICATION_ERROR = "APPLICATION_ERROR";

export const REMOVE_EVENT_SUCCESS = "REMOVE_EVENT_SUCCESS";
export const REMOVE_EVENT_ERROR = "REMOVE_EVENT_ERROR";

export const SELECT_ID_SUCCESS = "SELECT_ID_SUCCESS";

export const FILTER_SUCCESS = "FILTER_SUCCESS";

export const ADD_PLAYER_SUCCESS = "ADD_PLAYER_SUCCES";
export const ADD_PLAYER_ERROR = "ADD_PLAYER_ERROR";

export const SET_ERROR = "SET_ERROR";
